---
working_dir:  "/home/cachris/projects/geneva/hypoxia/analysis/"
bulk_rna_data_dir:  "/home/cachris/projects/geneva/hypoxia/data/TSHG12_QSP_ALS_hypoxia_RM_Kevan_GENEVA/"
star_genome:  "/home/genomes/hg38/star_hg38/"
sample_sheet: "/home/cachris/projects/geneva/hypoxia/data/TSHG12_QSP_ALS_hypoxia_RM_Kevan_GENEVA/sample_sheet.csv"

