---
SAMPLES : ["93E",  "41865",  "50073",  "32947_c7",  
          "50004",  "5MRLiCTR",  "2GW3iCTR",  "2PFYiCTR", 
          "6GNGiCTR",  "5JAZiALS",  "2WW0iALS",  "0YJYiALS",
          "2NDDiALS",  "0WD8iALS",  "0JCLiALS",  "AG0017",  
          "50000",  "35658",  "29iALS",  "12240",  "39B",  
          "3XLKiALS",  "184",  "6769",  "6769_c1",  "3719",  
          "10739",  "10689",  "13454",  "No4",  "SOD139B_1",
          "29iALS_ISO",  "2CLNiALS",  "2DDGiALS",  "ES", 
          "1B06",  "6GHCiALS",  "SOD139B_2",  "5FFPiALS",  
          "No3",  "12099",  "5280",  "3231",  "50007",  
          "OKVBiALS",  "2B09",  "39B_Corr",  "CS5HF7iALS",
          "CS2YNLiALS",  "5GR5iALS",  "1RUG",  "12100",  
          "AH9iALS",  "11813_fibs",  "10739_fibs",  
          "9292_fibs",  "13454_fibs",  "CS0KHAiALS",  
          "9711",  "14185",  "ND35663",  "CS0KBHiALS",  
          "ND09329",  "ND50082",  "BxPC3",  "SH4",  "LNCaP",
          "U87",  "786O",  "A375",  "Panc0504",  "Panc1005",
          "HCC1806",  "SU8686",  "HCT15",  "HPAC",  "HepG2",
          "HPAFII",  "SW1990",  "MDA231",  "PC3",  "SJSA1",  
          "143B",  "LN229",  "Caki1",  "Panc0203",  "Capan2",
          "Panc1",  "Hep3b",  "AGS",  "AsPC1",  "SW620",  
          "ND08957",  "ND08075"],
working_dir : "/home/cachris/geneva/hypoxia/analysis/",
bulk_rna_data_dir : "/home/cachris/geneva/hypoxia/data/",
star_genome : "/home/genomes/hg38/star_hg38/",
sample_sheet: "/home/cachris/geneva/hypoxia/data/TSHG12_QSP_ALS_hypoxia_RM_Kevan_GENEVA/sample_sheet.csv",
scRNA_samples : ["8-3_S10", "8-4_S11", "21-2_S12", "21-4_S13", 
                  "60-1_S14", "60-4_S15"],
scRNA_dir : "/home/cachris/geneva/hypoxia/data/TSHG10_hypoxia_GENEVA/",
cellranger_index : "/home/genomes/cellranger_refs/refdata-gex-GRCh38-2020-A/",
cellranger_output_path : ,
